name: 'Deploy ASP.NET Core app to Azure Web App'

on:
  push:
    branches:
      - "main"

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      # Checkout the repo
      - uses: actions/checkout@v2

  deploy-prod:
    runs-on: ubuntu-latest
    environment: 'prod'
    needs: deploy-dev
    steps:
      # Download published artifact
      - name: Download artifact
        run: echo "approved"
        
   
