name: Two Jobs with Approval

on:
  push:
    branches:
      - main

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job 1
        run: echo "Job 1 is running"

  wait-for-approval:
    runs-on: ubuntu-latest
    needs: job1
    steps:
      - name: Approval required
        uses: hmarr/approve-action@v2
        with:
          message: "Do you approve running Job 2?"

  job2:
    runs-on: ubuntu-latest
    needs: wait-for-approval
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Job 2
        run: echo "Job 2 is running"
